---
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - login
      - -u
      - mukeshravi
      - -p
      - Mkhsanjay@1997
      - hub.docker.com/repository/docker/mukeshravi/datahub_images/
  - name: gcr.io/cloud-builders/docker
    args:
      - pull
      - hub.docker.com/repository/docker/mukeshravi/datahub_images/
  - name: gcr.io/cloud-builders/docker
    args:
      - tag
      - hub.docker.com/repository/docker/mukeshravi/datahub_images/
      - gcr.io/nifty-vault-372307/gcf-artifacts/datahub-image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/nifty-vault-372307/gcf-artifacts/datahub-image
options:
  logging: NONE
