---

steps:

  - name: gcr.io/cloud-builders/docker

    entrypoint: bash

    args:

      - -c

      - docker login --username=$$DOCKER_USERNAME --password=$$DOCKER_PASSWORD

    secretEnv:

      - USERNAME

      - PASSWORD

  - name: gcr.io/cloud-builders/docker

    entrypoint: bash

    args:

      - -c

      - docker run $$DOCKER_USERNAME/datahub_images:fe_image_latest

    secretEnv:

      - USERNAME

availableSecrets:

  secretManager:

    - versionName: projects/ardent-iris-389305/secrets/DOCKER_PASSWORD/versions/1

      env: PASSWORD

    - versionName: projects/ardent-iris-389305/secrets/DOCKER_USERNAME/versions/1

      env: USERNAME

options:

  logging: NONE
