---
steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - >
        echo "$$DOCKER_PASSWORD" | docker login --username "$$DOCKER_USERNAME"
        --password-stdin
    secretEnv:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
  - name: gcr.io/cloud-builders/docker
    args:
      - pull
      - -t
      - mukeshravi/datahub_images:fe_image_latest
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-central1-docker.pkg.dev/nifty-vault-372307/gcf-artifacts/datahub-image
availableSecrets:
  secretManager:
    - versionName: projects/nifty-vault-372307/secrets/DOCKER_USERNAME/versions/1
      env: DOCKER_USERNAME
    - versionName: projects/nifty-vault-372307/secrets/DOCKER_PASSWORD/versions/1
      env: DOCKER_PASSWORD
options:
  logging: NONE

