---
steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker login --username="$$USERNAME" --password="$$PASSWORD"
    secretEnv: ['USERNAME', 'PASSWORD']
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker pull mukeshravi/datahub_images:pgdb_image_latest
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/nifty-vault-372307/gcf-artifacts/pg_datahub-image
      - .
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker push us-central1-docker.pkg.dev/nifty-vault-372307/gcf-artifacts/pg_datahub-image
    secretEnv: ['USERNAME', 'PASSWORD']
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker pull mukeshravi/datahub_images:be_image_latest
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/nifty-vault-372307/gcf-artifacts/be_datahub-image
      - .
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker push us-central1-docker.pkg.dev/nifty-vault-372307/gcf-artifacts/be_datahub-image
    secretEnv: ['USERNAME', 'PASSWORD']
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker pull mukeshravi/datahub_images:fe_image_latest
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/nifty-vault-372307/gcf-artifacts/fe_datahub-image
      - .
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker push us-central1-docker.pkg.dev/nifty-vault-372307/gcf-artifacts/fe_datahub-image
    secretEnv: ['USERNAME', 'PASSWORD']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth configure-docker
        gcloud compute ssh datahub-pvt-0 --project nifty-vault-372307 --zone us-east1-b --command='sudo apt-get update'
        gcloud compute scp image.tar datahub-pvt-0:~/ --zone=us-east1-b --internal-ip
        gcloud compute ssh datahub-pvt-0 --zone=us-east1-b --tunnel-through-iap --command "docker load -i image.tar"
        gcloud compute ssh datahub-pvt-0 --zone=us-east1-b --tunnel-through-iap --command "docker run -d -p 80:80 frontend:latest"
availableSecrets:
  secretManager:
  - versionName: projects/nifty-vault-372307/secrets/DOCKER_PASSWORD/versions/1
    env: 'PASSWORD'
  - versionName: projects/nifty-vault-372307/secrets/DOCKER_USERNAME/versions/1
    env: 'USERNAME'
options:
  logging: CLOUD_LOGGING_ONLY
