---
steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker login --username="$$DOCKER_USERNAME" --password="$$DOCKER_PASSWORD"
    secretEnv: ['DOCKER_USERNAME','DOCKER_PASSWORD']
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker pull mukeshravi/datahub_images:pgdb_image_latest
    secretEnv: ['DOCKER_USERNAME','DOCKER_PASSWORD']
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker pull mukeshravi/datahub_images:be_image_latest
    secretEnv: ['DOCKER_USERNAME','DOCKER_PASSWORD']
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker pull mukeshravi/datahub_images:fe_image_latest
    secretEnv: ['DOCKER_USERNAME','DOCKER_PASSWORD']
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/nifty-vault-372307/gcf-artifacts/datahub-image
      - .
    secretEnv: ['DOCKER_USERNAME','DOCKER_PASSWORD']
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - docker push
        us-central1-docker.pkg.dev/nifty-vault-372307/gcf-artifacts/datahub-image
    secretEnv: ['DOCKER_USERNAME','DOCKER_PASSWORD']
availableSecrets:
  secretManager:
    - versionName: projects/334893375712/secrets/DOCKER_PASSWORD/versions/1
      env: 'DOCKER_PASSWORD'
    - versionName: projects/334893375712/secrets/DOCKER_USERNAME/versions/1
      env: 'DOCKER_USERNAME'
options:
  logging: NONE


